### ISSUE TITLE
Reserved words in answers

### ISSUE THREAD

**Issue by elinw** [swirldev/swirlify#21]
Hi,

In multiple choice answers, using a [reserved word](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Reserved.html)  in an answer makes the testit() crash with a not helpful message (at least for me).  

I can see that you are in the midst of redoing the testing and testit() is deprecated so I'm a bit hesitant to send a PR, but will try to solve if you want me to.  It's a bit of a tricky issue because  really something that happens in Swirl not Swirlify, but I feel as though Swirlify should catch it more gracefully if possible. 

added: Maybe I should submit something about this to the swirl course gotcha lesson?

**Comment by seankross** [comment]
Does the same thing happen when using `demo_lesson()`?

**Comment by elinw** [comment]
No, it seems to work fine in demo_lesson().

Actually I was using the CRAN version, but in the github version it seems not to be an issue.

**Comment by seankross** [comment]
That's interesting, the CRAN version and the master branch on Github should be identical.

**Comment by elinw** [comment]
Maybe I had an older version?

**Comment by seankross** [comment]
What do you get as the result of `packageVersion("swirlify")`?

**Comment by elinw** [comment]
Well now I have ‘0.5.0’.

I’m not sure what I had before I did github_install().   Okay that's just weird, will update again.

**Comment by seankross** [comment]
Okay, sounds good. I'm going to close this issue, but feel free to reopen it if you have any other issues.
