### ISSUE TITLE
file.rename() versus file.copy()

### ISSUE THREAD

**Issue by elinw** [swirldev/swirlify#22]
Hi Sean,
I see that in most of the [install functions](https://github.com/swirldev/swirl/blob/master/R/install_course.R) file.rename() is used instead of file.copy().  This means that the existing course needs to be uninstalled before installing an updated version  (if an update option was added). Admittedly you would also have to do file.remove to clean up the first unzipped copy but for me, as I'm adding lessons to the server, it would be preferable not to have to uninstall.  If you agree, I'd be happy to send a PR for this change.

**Comment by seankross** [comment]
I agree with you, I need to look at this more closely.

**Comment by seankross** [comment]
Does this have anything to do with the manifest? (Asking because of issue title)

**Comment by elinw** [comment]
No, sorry, I started something about the manifest and then realized it was actually fixed in master. I actually changed the title.

Elin

**Comment by elinw** [comment]
I'm going to close this because it is really a bug in swirl and not in swirlify.
